config/routes.rb
Rails.application.routes.draw do
  resources :homes
  get 'home/index'

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/home.rb
class Home < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: [:show, :edit, :update, :destroy]

  # GET /homes
  # GET /homes.json
  def index
    @homes = Home.all
  end

  # GET /homes/1
  # GET /homes/1.json
  def show
  end

  # GET /homes/new
  def new
    @home = Home.new
  end

  # GET /homes/1/edit
  def edit
  end

  # POST /homes
  # POST /homes.json
  def create
    @home = Home.new(home_params)

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: 'Home was successfully created.' }
        format.json { render :show, status: :created, location: @home }
      else
        format.html { render :new }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homes/1
  # PATCH/PUT /homes/1.json
  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to @home, notice: 'Home was successfully updated.' }
        format.json { render :show, status: :ok, location: @home }
      else
        format.html { render :edit }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1
  # DELETE /homes/1.json
  def destroy
    @home.destroy
    respond_to do |format|
      format.html { redirect_to homes_url, notice: 'Home was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def home_params
      params.require(:home).permit(:title, :note)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="keywords" content="onepage, resume">

	<title>Yoana Dimova</title>
  <!-- Web Fonts -->
  <link href='http://fonts.googleapis.com/css?family=Roboto:400,300,500,700' rel='stylesheet' type='text/css'>
</head>

<body>
	<!-- Home Section -->
	<section id="home" class="tt-fullHeight" data-stellar-vertical-offset="50" data-stellar-background-ratio="0.2">
		<div class="intro">
			<div class="avatar-image"></div>
			<h1>Hi, <span>I'm Yoana</span></h1>
			<p>This is a WIP.</p>

      <div class="social-icons">
        <ul class="list-inline">
          <li><a href="https://www.linkedin.com/in/yoana-dimova-04b13482/"><i class="fa fa-linkedin"></i></a></li>
        </ul>
      </div> <!-- /.social-icons -->
		</div>

		<div class="mouse-icon">
			<div class="wheel"></div>
		</div>
	</section><!-- End Home Section -->

	<!-- Navigation -->
	<header class="header">
		<nav class="navbar navbar-custom" role="navigation">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#custom-collapse">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
				</div>

				<div class="collapse navbar-collapse" id="custom-collapse">
					<ul class="nav navbar-nav navbar-right">
						<li><a href="#home">Home</a></li>
						<li><a href="#skills">Skills</a></li>
						<li><a href="#resume">Resume</a></li>
					</ul>
				</div>
			</div><!-- .container -->
		</nav>
	</header><!-- End Navigation -->
    <!-- Skills Section -->
    <section id="skills" class="skills-section section-padding">
      <div class="container">
        <h2 class="section-title wow fadeInUp">Skills</h2>

        <div class="row">
          <div class="col-md-6">
            <div class="skill-progress">
              <div class="skill-title"><h3>HTML5</h3></div>
              <div class="progress">
                <div class="progress-bar six-sec-ease-in-out" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" ><span>80%</span>
                </div>
              </div><!-- /.progress -->
            </div><!-- /.skill-progress -->

            <div class="skill-progress">
              <div class="skill-title"><h3>CSS3</h3></div>
              <div class="progress">
                <div class="progress-bar six-sec-ease-in-out" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" ><span>80%</span>
                </div>
              </div><!-- /.progress -->
            </div><!-- /.skill-progress -->
            <div class="skill-progress">
              <div class="skill-title"><h3>Javascript</h3></div>
              <div class="progress">
                <div class="progress-bar six-sec-ease-in-out" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" ><span>80%</span>
                </div>
              </div><!-- /.progress -->
            </div><!-- /.skill-progress -->
          </div><!-- /.col-md-6 -->

          <div class="col-md-6">
            <div class="skill-progress">
              <div class="skill-title"><h3>SASS</h3></div>
              <div class="progress">
                <div class="progress-bar six-sec-ease-in-out" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" ><span>80%</span>
                </div>
              </div><!-- /.progress -->
            </div><!-- /.skill-progress -->
            <div class="skill-progress">
              <div class="skill-title"><h3>Bootstrap 3/4</h3></div>
              <div class="progress">
                <div class="progress-bar six-sec-ease-in-out" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" ><span>75%</span>
                </div>
              </div><!-- /.progress -->
            </div><!-- /.skill-progress -->
            <div class="skill-progress">
              <div class="skill-title"><h3>UI/UX Design</h3></div>
              <div class="progress">
                <div class="progress-bar six-sec-ease-in-out" role="progressbar" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100" ><span>70%</span>
                </div>
              </div><!-- /.progress -->
            </div><!-- /.skill-progress -->
          </div><!-- /.col-md-6 -->
					<div class="col-md-6">
						<div class="skill-progress">
							<div class="skill-title"><h3>Java</h3></div>
							<div class="progress">
								<div class="progress-bar six-sec-ease-in-out" role="progressbar" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100" ><span>70%</span>
								</div>
							</div><!-- /.progress -->
						</div><!-- /.skill-progress -->
						<div class="skill-progress">
							<div class="skill-title"><h3>Frontend Dev</h3></div>
							<div class="progress">
								<div class="progress-bar six-sec-ease-in-out" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" ><span>80%</span>
								</div>
							</div><!-- /.progress -->
						</div><!-- /.skill-progress -->
						<div class="skill-progress">
							<div class="skill-title"><h3>Android Dev</h3></div>
							<div class="progress">
								<div class="progress-bar six-sec-ease-in-out" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" ><span>60%</span>
								</div>
							</div><!-- /.progress -->
						</div><!-- /.skill-progress -->
					</div><!-- /.col-md-6 -->
        </div><!-- /.row -->
      </div><!-- /.container -->
    </section><!-- End Skills Section -->
		<!-- Resume Section -->
    <section id="resume" class="resume-section section-padding">
        <div class="container">
            <h2 class="section-title wow fadeInUp">Resume</h2>
            <div class="row">
                <div class="col-md-12">
                    <div class="resume-title">
                        <h3>Education <i class="fa fa-graduation-cap" aria-hidden="true"></i></h3>
                    </div>
                    <div class="resume">
                        <ul class="timeline">

                            <li class="timeline-inverted">
                                <div class="posted-date">
                                    <span class="month">2013-2017</span>
                                </div><!-- /posted-date -->

                                <div class="timeline-panel wow fadeInUp">
                                    <div class="timeline-content">
                                        <div class="timeline-heading">
                                            <h3>BSc Media informatics</h3>
                                            <span>Ludwig-Maximilian University of Munich</span>
                                        </div><!-- /timeline-heading -->

                                        <div class="timeline-body">
                                            <p>Computer Science with human-computer-interaction minor</p>
                                        </div><!-- /timeline-body -->
                                    </div> <!-- /timeline-content -->
                                </div> <!-- /timeline-panel -->
                            </li>

                            <li>
                                <div class="posted-date">
                                  <span class="month">2008-2013</span>
                                </div><!-- /posted-date -->

                                <div class="timeline-panel wow fadeInUp">
                                    <div class="timeline-content">
                                        <div class="timeline-heading">
                                            <h3>High school diploma</h3>
                                            <span>91. Deutsches Gymnasium in Sofia, Bulgaria</span>
                                        </div><!-- /timeline-heading -->

                                        <div class="timeline-body">
                                            <p></p>
                                        </div><!-- /timeline-body -->
                                    </div> <!-- /timeline-content -->
                                </div><!-- /timeline-panel -->
                            </li>
                        </ul>
                    </div>
                </div>
            </div><!-- /row -->
            <div class="row" style="margin-bottom: 50px;">
                <div class="col-md-12">
                    <div class="resume-title">
                        <h3>Experience <i class="fa fa-briefcase" aria-hidden="true"></i></h3>
                    </div>
                    <div class="resume">
                        <ul class="timeline">
														<li class="timeline-inverted">
																<div class="posted-date">
																	<span class="month">2017-today</span>
																</div><!-- /posted-date -->

																<div class="timeline-panel wow fadeInUp">
																		<div class="timeline-content">
																				<div class="timeline-heading">
																						<h3>Junior Software Developer</h3>
																						<span>Experteer GmbH</span>
																				</div><!-- /timeline-heading -->

																				<div class="timeline-body">
																						<p></p>
																				</div><!-- /timeline-body -->
																		</div> <!-- /timeline-content -->
																</div><!-- /timeline-panel -->
														</li>
														<li>
																<div class="posted-date">
																	<span class="month">2015-2017</span>
																</div><!-- /posted-date -->

																<div class="timeline-panel wow fadeInUp">
																		<div class="timeline-content">
																				<div class="timeline-heading">
																						<h3>Working student in frontend-development</h3>
																						<span>Experteer GmbH</span>
																				</div><!-- /timeline-heading -->

																				<div class="timeline-body">
																						<p></p>
																				</div><!-- /timeline-body -->
																		</div> <!-- /timeline-content -->
																</div><!-- /timeline-panel -->
														</li>
														<li class="timeline-inverted">
																<div class="posted-date">
																	<span class="month">2014-2015</span>
																</div><!-- /posted-date -->

																<div class="timeline-panel wow fadeInUp">
																		<div class="timeline-content">
																				<div class="timeline-heading">
																						<h3>Web Design Assistant</h3>
																						<span>Mapp Digital (Teradata)</span>
																				</div><!-- /timeline-heading -->

																				<div class="timeline-body">
																						<p></p>
																				</div><!-- /timeline-body -->
																		</div> <!-- /timeline-content -->
																</div> <!-- /timeline-panel -->
														</li>
                        </ul>
                    </div>
                </div>
            </div><!-- /row -->
						<div class="row">
								<div class="col-md-12">
										<div class="resume-title">
												<h3>Other projects <i class="fa fa-heart" aria-hidden="true"></i></h3>
										</div>
										<div class="resume">
												<ul class="timeline">

														<li>
																<div class="posted-date">
																		<span class="month">2017-now</span>
																</div><!-- /posted-date -->

																<div class="timeline-panel wow fadeInUp">
																		<div class="timeline-content">
																				<div class="timeline-heading">
																						<h3>Hackathons Coordinator</h3>
																						<span>Female Tech Leaders</span>
																				</div><!-- /timeline-heading -->

																				<div class="timeline-body">
																						<p>I like to share my passion for coding with others and in my free time I organize hackathons in Munich on topics like "Machine Learning", "Social Infotainment" and many others :) </p>
																				</div><!-- /timeline-body -->
																		</div> <!-- /timeline-content -->
																</div> <!-- /timeline-panel -->
														</li>
												</ul>
										</div>
								</div>
						</div><!-- /row -->
        </div><!-- /.container -->
    </section><!-- End Resume Section -->


	<!-- Footer Section -->
    <footer class="footer-wrapper">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="copyright text-center">
              <p>&copy; All rights reserved.</p>
            </div>
          </div>
        </div>
      </div>
    </footer><!-- End Footer Section -->


	<!-- Scroll-up -->
	<div class="scroll-up">
		<a href="#home"><i class="fa fa-angle-up"></i></a>
	</div>

	<!-- Javascript files -->
  <script src="http://a.vimeocdn.com/js/froogaloop2.min.js"></script>
</body>
</html>

app/views/homes/_form.html.erb
<%= form_for(home) do |f| %>
  <% if home.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(home.errors.count, "error") %> prohibited this home from being saved:</h2>

      <ul>
      <% home.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :note %>
    <%= f.text_field :note %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/homes/edit.html.erb
<h1>Editing Home</h1>

<%= render 'form', home: @home %>

<%= link_to 'Show', @home %> |
<%= link_to 'Back', homes_path %>

app/views/homes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Homes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Note</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @homes.each do |home| %>
      <tr>
        <td><%= home.title %></td>
        <td><%= home.note %></td>
        <td><%= link_to 'Show', home %></td>
        <td><%= link_to 'Edit', edit_home_path(home) %></td>
        <td><%= link_to 'Destroy', home, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Home', new_home_path %>

app/views/homes/new.html.erb
<h1>New Home</h1>

<%= render 'form', home: @home %>

<%= link_to 'Back', homes_path %>

app/views/homes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @home.title %>
</p>

<p>
  <strong>Note:</strong>
  <%= @home.note %>
</p>

<%= link_to 'Edit', edit_home_path(@home) %> |
<%= link_to 'Back', homes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsProject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>